config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :searches, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  devise_scope :user do
    post :set_email, controller: :omniauth_callbacks, as: :set_user_email
  end

  use_doorkeeper

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable], except: [:index, :show, :new] do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Authorable
  include Votable
  include Commentable

  has_many :answers, -> { order('best desc') }, dependent: :destroy
  has_many :subscribes, dependent: :destroy

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :subscribe_author

  scope :last_day, -> {  where('created_at >= ?', (Date.today - 1.day).to_time) }

  private

  def subscribe_author
    subscribes.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource class: Question

  def index
    respond_with Question.all
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionFullSerializer
  end

  def create
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :build_answer, only: [:show]
  before_action :build_attachments, only: [:edit]
  after_action :publish_question, only: [:create]

  respond_to :js, only: [:update]
  respond_to :json

  authorize_resource

  include Voted

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def edit; end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
        'questions',
        @question.to_json
    )
  end

  def build_answer
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def build_attachments
    @question.attachments.build
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:_destroy, :id, :file])
  end
end

app/views/questions/_form.html.slim
= simple_form_for @question do |f|
  = f.error_notification
  = f.input :title, input_html: { class: 'form-control' }, label: 'Title -'
  = f.input :body, input_html: { class: 'form-control', rows: 15 }, label: 'Body -'

  .form-group
    = render 'shared/nested_form/attachments_form', f: f, attachable: @question

  = f.button :submit, class: 'btn btn-primary'

app/views/questions/edit.html.slim
- content_for :title, @question.title.present? ? @question.title : 'Edit Question'

h1 = 'Edit Question'
== render 'form'

app/views/questions/index.html.slim
h2 Questions list

ul.questions.list-unstyled
  - @questions.each do |question|
    li[data-question="#{question.id}"]
      .content
        h5 = link_to question.title, question_path(question)

app/views/questions/new.html.slim
- content_for :title, 'New Question'

h1 = 'New Question'
== render 'form'

app/views/questions/show.html.slim
.question id="question_#{@question.id}" data-question-id="#{@question.id}"
  - if can?(:update, @question) && can?(:destroy, @question)
    = link_to 'Edit', edit_question_path(@question), class: 'btn btn-primary'
    = link_to 'Delete', question_path(@question), method: :delete, class: 'btn btn-danger'

  - cache @question do
    p = @question.title
    p = @question.body
    p
      = render partial: 'shared/nested_form/attachments', locals: { object: @question }

  p
    = render 'shared/votes_panel', object: @question
  div.clearfix

  - if current_user && current_user.has_subscribe?(@question)
    = link_to 'Unsubscribe', subscribe_path(current_user.get_subscribe(@question)), remote: true, method: :delete, id: 'unsubscribe_btn', class: 'btn btn-primary'
  - else
    - if can?(:create, Subscribe)
      = link_to 'Subscribe', question_subscribes_path(@question), remote: true, method: :post, id: 'subscribe_btn', class: 'btn btn-primary'

  p
    = render 'comments/comments', commentable: @question

  h2#answers-title = pluralize(@question.answers.count, 'answer')
  - if @question.answers.present?
    ul.answers.list-unstyled
      = render @question.answers

  - if can?(:create, Answer)
    = render 'answers/form', question: @question, answer: @answer
  - else
    = link_to 'Sign in to answer the Question', new_user_session_path