config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :searches, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  devise_scope :user do
    post :set_email, controller: :omniauth_callbacks, as: :set_user_email
  end

  use_doorkeeper

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable], except: [:index, :show, :new] do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Authorable
  include Votable
  include Commentable

  belongs_to :question, touch: true

  after_create :notify_subscribed_users

  validates :body, presence: true
  validates :best, uniqueness: { scope: :question_id }, if: :best?

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def make_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
    end
  end

  private

  def notify_subscribed_users
    NotifySubscribedUsersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:edit, :update, :destroy, :best]
  before_action :set_question, only: [:create]
  after_action :publish_answer, only: [:create]

  authorize_resource

  include Voted

  def edit; end

  def create
    @answer = @question.answers.new(answer_params.merge(user: current_user))
    @answer.save
  end

  def update
    if @answer.update(answer_params)
      redirect_to @answer.question
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    flash[:notice] = 'Answer was successfully deleted.'
    redirect_to @answer.question
  end

  def best
    authorize! :best, @answer

    @answer.make_best
    flash[:notice] = 'Answer marked as best'
    redirect_to @answer.question
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
        "answers_#{@question.id}",
        { answer: @answer, attachments: @answer.attachments }.to_json
    )
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:_destroy, :id, :file])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource class: Answer

  def index
    question = Question.find(params[:question_id])
    respond_with question.answers.reorder('id')
  end

  def show
    answer = Answer.find(params[:id])
    respond_with answer, serializer: AnswerFullSerializer
  end

  def create
    question = Question.find(params[:question_id])
    respond_with(@answer = question.answers.create(answer_params.merge(user: current_resource_owner)))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  li.answer[id="answer_#{answer.id}"]
    p
      = render 'shared/votes_panel', object: answer
    div
      - if answer.best?
        strong Best answer
        br

      - cache answer do
        p= answer.body
        = render partial: 'shared/nested_form/attachments', locals: { object: answer }
        = render 'comments/comments', commentable: answer

      - if !answer.best? && can?(:best, answer)
        = link_to 'Make Best', best_answer_path(answer), method: :patch, remote: true
      - if can?(:destroy, answer)
        = link_to 'Delete', answer, method: :delete, class: 'btn btn-danger', remote: true
      - if can?(:update, answer)
        = link_to 'Edit', answer, class: 'btn btn-primary edit-answer', data: { 'answer-id': answer.id }
        p
          = simple_form_for answer, remote: true do |f|
            = f.error_notification
            = f.input :body, input_html: { class: 'form-control' }, label: 'Your answer -'
            .form-group
              = render 'shared/nested_form/attachments_form', f: f, attachable: answer
            = f.button :submit, 'Update', class: 'btn btn-primary'

    div.clearfix

app/views/answers/_form.html.slim
= simple_form_for [question, answer], remote: true do |f|
  = f.error_notification
  = f.input :body, input_html: { class: 'form-control' }, label: 'Your answer -'
  .form-group
    = render 'shared/nested_form/attachments_form', f: f, attachable: answer
  = f.button :submit, class: 'btn btn btn-primary'

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
  $('#new_answer').replaceWith('<%= j render 'answers/form', question: @question, answer: @answer %>')
<% else %>
  $('#new_answer').replaceWith('<%= j render 'answers/form', question: @question, answer: @question.answers.new %>')
<% end %>