config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :searches, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  devise_scope :user do
    post :set_email, controller: :omniauth_callbacks, as: :set_user_email
  end

  use_doorkeeper

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :answers, concerns: [:votable, :commentable], except: [:index, :show, :new] do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.slim
doctype html
html.no-js[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title = 'Stack overflow'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = Gon::Base.render_data
  body
    header
      .contain-to-grid.navbar.navbar-default
        nav.top-bar[data-topbar role="navigation"]
          ul.nav.navbar-nav
            - if user_signed_in?
              li = link_to "Signed in as #{current_user.email}", edit_user_registration_path
              li = link_to 'Sign out', destroy_user_session_path, method: :delete
            - else
              li = link_to 'Sign in', new_user_session_path
              li = link_to 'Sign up', new_user_registration_path
            li
              = link_to 'View questions', questions_path
            li.has-form.show-for-small-only
              = link_to 'Ask Question', new_question_path, class: 'button'

    div#flash

    .container
      = render 'searches/form', form_class: 'navbar-form navbar-right'

      .row
        article.medium-12.columns
          = yield
        footer

      - if flash.present?
        .alert-boxes
          - flash.each do |key, value|
            .alert[data-alert role="alert" class="alert-dismissible #{alert_class(key)}"]
              button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
                span[aria-hidden="true"] ×

              = value + ' '